### ISSUE TITLE
国际版登录后卡住

### ISSUE THREAD

**Issue by walterclozet** [YumeMichi/elichika#1]
国际版登录后在
/bootstrap/fetchBootstrap?p=a&mv=2d61e7b4e89961c7&id=2&u=588296696&t=1689260836535&l=zh
步骤卡住, 游戏会在一个空白页面. 也没有now loading的显示. 确认过RSA key已经替换过了, 是不是国际版的asset不一样呢?
这是config.json的配置.
{"app_name":"elichika","settings":{"is_global":true,"master_version":"2d61e7b4e89961c7","startup_key":"Q3YasOdwAkNh2GmZ","cdn_server":"http://192.168.31.2:8081/static"}}

**Comment by YumeMichi** [comment]
可以试一下最新的代码以及3.12.0客户端

**Comment by walterclozet** [comment]
> 可以试一下最新的代码以及3.12.0客户端

我之前安装过最新的, 安装完主界面会显示6.30停止运营, 点击后会用浏览器打开官网, 所以降级到3.11了. 不过我下载的国际版db没有master_a_zh, 只有master_i_zh所以把master_i_zh改成master_data_a_zh了, 不知道有没有关系?

**Comment by YumeMichi** [comment]
> > 可以试一下最新的代码以及3.12.0客户端
> 
> 我之前安装过最新的, 安装完主界面会显示6.30停止运营, 点击后会用浏览器打开官网, 所以降级到3.11了. 不过我下载的国际版db没有master_a_zh, 只有master_i_zh所以把master_i_zh改成master_data_a_zh了, 不知道有没有关系?

根据文档里来

**Comment by walterclozet** [comment]
> 

根据文档重来了一次, 显示
[GIN] 2023/07/15 - 08:51:43 | 200 |   14.667689ms |    192.168.31.3 | POST     "/login/startup?p=a&id=1&l=zh"
[GIN] 2023/07/15 - 08:51:43 | 404 |      51.986µs |    192.168.31.3 | GET      "/static/2d61e7b4e89961c7/masterdata_a_zh"
重新确认了下, 文档中提供的as国际版中没有这个文件, 只有masterdata_i_zh文件.

**Comment by YumeMichi** [comment]
> > 
> 
> 根据文档重来了一次, 显示 [GIN] 2023/07/15 - 08:51:43 | 200 | 14.667689ms | 192.168.31.3 | POST "/login/startup?p=a&id=1&l=zh" [GIN] 2023/07/15 - 08:51:43 | 404 | 51.986µs | 192.168.31.3 | GET "/static/2d61e7b4e89961c7/masterdata_a_zh" 重新确认了下, 文档中提供的as国际版中没有这个文件, 只有masterdata_i_zh文件.
> 
> 经过比对国际服的db文件缺少安卓平台需要的masterdata_a_zh, asset_a_zh.db dictionary_zh_android.db这3个文件, 只有ios平台的. 不知您这边有这几个文件吗?

文档里有下载地址啊

**Comment by walterclozet** [comment]
> 

文档里提供的国际版asdb中缺少安卓平台需要的masterdata_a_zh, asset_a_zh.db dictionary_zh_android.db这3个文件. 
我是在8823上的全量数据包/asdb下载的.

**Comment by YumeMichi** [comment]
> > 
> 
> 文档里提供的国际版asdb中缺少安卓平台需要的masterdata_a_zh, asset_a_zh.db dictionary_zh_android.db这3个文件. 我是在8823上的全量数据包/asdb下载的.

本项目的readme

**Comment by walterclozet** [comment]
非常感谢, 已经搞定了
