### ISSUE TITLE
新版本游戏无法登录

### ISSUE THREAD

**Issue by walterclozet** [YumeMichi/elichika#2]
更新今天中午更新最新版本后, 启动游戏提示发生错误即将返回标题画面. 国际服. 以前用的旧版本(就是config.json需要配置is_global的早期版本没有问题).
[xorm] [info]  2023/07/22 06:09:44.124026 PING DATABASE sqlite
[GIN] 2023/07/22 - 06:09:57 | 200 |    4.190313ms |       127.0.0.1 | POST     "/login/startup?p=a&id=1&l=zh"

**Comment by YumeMichi** [comment]
> 更新今天中午更新最新版本后, 启动游戏提示发生错误即将返回标题画面. 国际服. 以前用的旧版本(就是config.json需要配置is_global的早期版本没有问题). [xorm] [info] 2023/07/22 06:09:44.124026 PING DATABASE sqlite [GIN] 2023/07/22 - 06:09:57 | 200 | 4.190313ms | 127.0.0.1 | POST "/login/startup?p=a&id=1&l=zh"

仅支持3.12.0客户端

**Comment by walterclozet** [comment]
> 
你好, 我用了3.12.0客户端, 按照国服教程使用apktool 2.7.0解包替换打包后重新签名会提示无效的apk无法安装. 按照国际服教程使用7zip直接替换apk中的global-metadata.dat安装后启动闪退. 是否有新的修改方式?

**Comment by zhtg-cxxc** [comment]
> > 
> 
> 你好, 我用了3.12.0客户端, 按照国服教程使用apktool 2.7.0解包替换打包后重新签名会提示无效的apk无法安装. 按照国际服教程使用7zip直接替换apk中的global-metadata.dat安装后启动闪退. 是否有新的修改方式?

高版本安卓好像对安装包对齐有要求，签名之前，需要对重新打包的apk先zipalign一下。我在这里卡了半小时，然后用[APKToolGUI](https://github.com/AndnixSH/APKToolGUI)对齐之后装上了

**Comment by walterclozet** [comment]
> > > 
> > 
> > 
> > 你好, 我用了3.12.0客户端, 按照国服教程使用apktool 2.7.0解包替换打包后重新签名会提示无效的apk无法安装. 按照国际服教程使用7zip直接替换apk中的global-metadata.dat安装后启动闪退. 是否有新的修改方式?
> 
> 高版本安卓好像对安装包对齐有要求，签名之前，需要对重新打包的apk先zipalign一下。我在这里卡了半小时，然后用[APKToolGUI](https://github.com/AndnixSH/APKToolGUI)对齐之后装上了

zipaligned之后签名是可以安装上了, 不过启动闪退了... 就替换了个global-metadata.dat而已.
