### ISSUE TITLE
error when downloading data from cdn

### ISSUE THREAD

**Issue by joseph23pronton** [YumeMichi/elichika#5]
hello, how can i fix this or how do i decrypt the files needed for the cdn? i followed the links but nothing leads the way except for unpack_metapackages.py which is not working and always producing 
D:\Project All-Star!\elichika> & C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/python3.8.exe "d:/Project All-Star!/unpack_metapackages.py" "D:\sifdata\asset_a_en.db", "D:\sifdata\sifas-gl-cdn-assets-2d61e7b4e89961c7.tar"                                              
Traceback (most recent call last):
  File "d:/Project All-Star!/unpack_metapackages.py", line 89, in <module>
    main()
  File "d:/Project All-Star!/unpack_metapackages.py", line 85, in main
    perform_unpack(args.asset_database, args.archive_fs)
  File "d:/Project All-Star!/unpack_metapackages.py", line 43, in perform_unpack
    db = sqlite3.connect(f"file:{database}?mode=ro", uri=True)
sqlite3.OperationalError: unable to open database file

Here's the error in the console of elichika:
[GIN] 2023/08/15 - 16:03:59 | 200 |    160.0393ms |     192.168.1.9 | POST     "/login/login?p=a&mv=2d61e7b4e89961c7&id=2&u=588296696&t=1692086639729&l=en"
[GIN] 2023/08/15 - 16:07:01 | 200 |     56.3452ms |     192.168.1.9 | POST     "/asset/getPackUrl?p=a&mv=2d61e7b4e89961c7&id=3&u=588296696&t=1692086821576&l=en"
[GIN] 2023/08/15 - 16:07:01 | 404 |       820.3µs |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/6oy69z"
[GIN] 2023/08/15 - 16:07:01 | 404 |       173.6µs |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/6oy69z"
[GIN] 2023/08/15 - 16:07:01 | 404 |      1.0405ms |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/jjze2p"
[GIN] 2023/08/15 - 16:07:01 | 404 |         408µs |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/lijvp6"
[GIN] 2023/08/15 - 16:07:01 | 404 |        89.1µs |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/yuro6n"
[GIN] 2023/08/15 - 16:07:01 | 404 |            0s |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/jjze2p"
[GIN] 2023/08/15 - 16:07:01 | 404 |      1.0076ms |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/yuro6n"
[GIN] 2023/08/15 - 16:07:01 | 404 |       857.4µs |     192.168.1.9 | GET      "/static/2d61e7b4e89961c7/lijvp6"

**Comment by YumeMichi** [comment]
you need to download database files, check readme file

**Comment by YumeMichi** [comment]
you need to put all the files into `2d61e7b4e89961c7` directory

**Comment by joseph23pronton** [comment]
this is what i got after doing that
![image](https://github.com/YumeMichi/elichika/assets/67457574/2ada2fa7-4da0-476e-ada3-3b38f381bb11)

**Comment by joseph23pronton** [comment]
it works now, all i need to do is to put all the files to the static/2d61e7b4e89961c7 as it was needed to update and download assets from the server
