### ISSUE TITLE
Download error when proceeding to download app assets for first time (GL version)

### ISSUE THREAD

**Issue by patiradumi** [YumeMichi/elichika#8]
After I choose English language for the app, then after the size of downloads is confirmed, the app shows this message:
![Screenshot_20240217-153247](https://github.com/YumeMichi/elichika/assets/108324792/7a4b9089-62d8-4479-b44b-51cdc9590cb9)
And this is the log message from server:
![image](https://github.com/YumeMichi/elichika/assets/108324792/156fd30e-4e3d-44f9-aafe-b51fcde3ce1b)

I have followed this [doc](https://codeberg.org/arina999999997/ll-hax-docs/src/branch/main/docs/sifas#user-content-easy-install) with my modifications:
1. I use Nox to emulate Samsung Note10+, 64bit, Android 7 
2. Modify the `global-metadata.dat` IP to 127.0.0.1:8081
3. The elichika server is run on port 8080 on the same PC with emulator
4. so I use command `nox_adb.exe reverse tcp:8081 tcp:8080`
5. I download CDN assets `sifas-gl-cdn-assets-2d61e7b4e89961c7.tar` from torrent
6. The client and database are from `LLAS patched files` (the MEGA file)
7. I have tried `adb reverse tcp:8081 tcp:8080`, nothing changed

Sorry for my English
Any help would be very very appreciated!

**Comment by YumeMichi** [comment]
have you modified the configuration file `config.json`?

**Comment by patiradumi** [comment]
Do you mean this file?
![image](https://github.com/YumeMichi/elichika/assets/108324792/5cb6bd0e-b904-40d4-8e54-f04c7005900a)

**Comment by YumeMichi** [comment]
> Do you mean this file? ![image](https://private-user-images.githubusercontent.com/108324792/305711771-5cb6bd0e-b904-40d4-8e54-f04c7005900a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTc3NDksIm5iZiI6MTcwODI1NzQ0OSwicGF0aCI6Ii8xMDgzMjQ3OTIvMzA1NzExNzcxLTVjYjZiZDBlLWI5MDQtNDBkNC04ZTU0LWYwNGM3MDA1OTAwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTU3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTgwZmYxODRlMWJmOTNkOTk3ODc0ZWI0MGYyMDNlODNhZDQ5MjczMDdhZDE4Y2Y0Njg5YWY0ZjI1OWNjYTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2WT5bkuqttrEY_Q3wm3MInlkfrWLpHE44U2MUnLFwQ8) In this directory? ![image](https://private-user-images.githubusercontent.com/108324792/305711865-897b67e5-a31a-40d4-9465-d9c4897fc8fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTc3NDksIm5iZiI6MTcwODI1NzQ0OSwicGF0aCI6Ii8xMDgzMjQ3OTIvMzA1NzExODY1LTg5N2I2N2U1LWEzMWEtNDBkNC05NDY1LWQ5YzQ4OTdmYzhmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTU3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGIwMmYwMjY4YjdhYjRmYjM5ZWNhNjczNGE1MDQ4N2FkNDE0ZTZiOGE0MDZhMWY2ZDE3ZDBhZjZiYTk4NWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dacYjbOjuESKJ31FzwHbW_Aro7RIwbyZClBTywhfqys)

yes, i think you need to use 8081 just like in global-metadata.dat

**Comment by patiradumi** [comment]
I edit `config.json` as you suggested and rerun, but the same error occurred. This time the elichika server log message changed.
![image](https://github.com/YumeMichi/elichika/assets/108324792/42f065e9-9b38-4a20-b6f0-4d4d0e0910f0)

**Comment by YumeMichi** [comment]
> I edit `config.json` as you suggested and rerun, but the same error occurred. This time the elichika server log message changed. ![image](https://private-user-images.githubusercontent.com/108324792/305723712-42f065e9-9b38-4a20-b6f0-4d4d0e0910f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzc1MDIsIm5iZiI6MTcwODMzNzIwMiwicGF0aCI6Ii8xMDgzMjQ3OTIvMzA1NzIzNzEyLTQyZjA2NWU5LTliMzgtNGEyMC1iNmYwLTRkNGQwZTA5MTBmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxMDA2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2Y3YjhkZGJhOGY5YWZmNzllODNiMjYyMTYxMjM2OWNkM2JlZmUyM2EwYzY0NmE2ZGQwODRiYzQ2NGRiMTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ji7nnqbt-gtbjZEMjaTnq-15goih2eLHWpxvScncOqY) In the app's download option, I chose Option 3 which downloads 5 GB and removes data when closing the app.

i saw 404 in your requests, i guessed you didn't put game data files into correct folder

**Comment by patiradumi** [comment]
I followed this [doc](https://codeberg.org/arina999999997/ll-hax-docs/src/branch/main/docs/sifas) which tells just to put data in `elichika/static/2d61e7b4e89961c7`. Could you explain the exact folder structure?
**What I have done:**
1. I extract `sifas-gl-cdn-assets-2d61e7b4e89961c7.tar` get folder  `sifas-gl-cdn-assets-2d61e7b4e89961c7` which I have put this folder in `elichika/static/2d61e7b4e89961c7`.
2. After extract `sifas-gl-live-masterdata-2d61e7b4e89961c7_rekeyed.tar`, I put all files in folder `sifas-gl-live-masterdata-2d61e7b4e89961c7_rekeyed` in `elichika/static/2d61e7b4e89961c7`.

**Comment by YumeMichi** [comment]
> I followed this [doc](https://codeberg.org/arina999999997/ll-hax-docs/src/branch/main/docs/sifas) which tells just to put data in `elichika/static/2d61e7b4e89961c7`. Could you explain the exact folder structure? And, do I have to decrypt the CDN data too? **What I have done:**
> 
> 1. I extract `sifas-gl-cdn-assets-2d61e7b4e89961c7.tar` get folder  `sifas-gl-cdn-assets-2d61e7b4e89961c7` which I have put this folder in `elichika/static/2d61e7b4e89961c7`.
> 2. After extract `sifas-gl-live-masterdata-2d61e7b4e89961c7_rekeyed.tar`, I put all files in folder `sifas-gl-live-masterdata-2d61e7b4e89961c7_rekeyed` in `elichika/static/2d61e7b4e89961c7`.

you can just simply use the cdn server in his document

**Comment by patiradumi** [comment]
I change a string in `config.json` to `https://llsifas.catfolk.party/static` and it works! After finishing download the app is playable even without internet. @YumeMichi Thank you for helping me.
